# see: https://help.cybozu.com/ja/general/admin/timezone.html
- name: ensure Etc/GMT timezone
  copy: content=Etc/GMT dest=/etc/timezone backup=yes
  register: timezone

- name: ensure timezone is updated
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: timezone.changed

- apt: upgrade=safe update_cache=yes force=yes
  tags: safe-upgrade

- apt: upgrade=dist update_cache=yes force=yes
  tags: dist-upgrade

- name: Install some basic packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - ntp
    - build-essential
    - tmux
    - vim
    - python3-pip
  tags: common_package

##################################################################
# tmux
##################################################################
- template: src=tmux/.tmux.conf dest=/root/.tmux.conf
  tags: tmux

##################################################################
# vim
##################################################################

- template: src=vim/.vimrc dest=/root/.vimrc
  tags: vim

- name: set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  tags: vim

##################################################################
# swap
##################################################################
- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count={{ swap_count }}
  when: ansible_swaptotal_mb < 1
  tags: swap

- name: Make swap
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 1
  tags: swap

- name: Add to fstab
  action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present
  tags: swap

- name: Turn swap on
  command: swapon -a
  tags: swap

- name: Set swapiness
  shell: echo 0 | sudo tee /proc/sys/vm/swappiness
  tags: swap

##################################################################
# pip
##################################################################
- name: Upgrade pip
  command: pip install --upgrade pip install --upgrade pip
  tags: pip

##################################################################
# install pip packages
##################################################################
- name: Install numpy, matplotlib
  command: pip install numpy matplotlib
  tags: pip
